version: '3.8'
services:
  db:
   image: mysql/mysql-server
   container_name: mysql_db
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=advjava
     - MYSQL_USER=admin
     - MYSQL_PASSWORD=root
   ports:
     - "3306:3306"

  app:
   image: sprbootjpa
   container_name: sprjpa
   ports:
     - 8080:8080
   environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/database?autoReconnect=true&useSSL=false
     SPRING_DATASOURCE_USERNAME: admin
     SPRING_DATASOURCE_PASSWORD: root
   depends_on:
     - db